name: "Upload ACUL Assets to GCS"
description: "Uploads ACUL build assets to GCS with proper cache settings"
inputs:
  working-directory:
    description: "Working directory relative to repository root"
    required: true
    default: "."
  gcs-bucket-name:
    description: "Name of the GCS bucket to upload to"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Sync the entire dist/ directory to the root of the GCS bucket.
        #
        #   --delete-unmatched-destination-objects
        #     Deletes files in GCS that are not in the local dist/ directory.
        #
        #   --cache-control
        #     Sets cache headers. (Uses a long max-age assuming hashed
        #     filenames).
        echo "Syncing ./dist to gs://${{ inputs.gcs-bucket-name }}/"
        gcloud storage rsync ./dist gs://${{ inputs.gcs-bucket-name }}/ \
          --recursive \
          --delete-unmatched-destination-objects \
          --quiet \
          --cache-control="max-age=31536000,public,immutable"

        echo "✅ Assets successfully uploaded to GCS bucket: ${{ inputs.gcs-bucket-name }}"
